"""Add recurrence, effort, and dependency models

Revision ID: 35c3c7a2e77a
Revises: 59aedd4daf5f
Create Date: 2026-02-20 05:20:35.571557+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c3c7a2e77a'
down_revision: Union[str, None] = '59aedd4daf5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blocker_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.Enum('HARD', 'SOFT', name='dependencytype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['responsibilities.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['responsibilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_dependency_blocker_blocked')
    )
    # Create complexitylevel type explicitly
    complexity_enum = sa.Enum('LOW', 'MEDIUM', 'HIGH', name='complexitylevel')
    complexity_enum.create(op.get_bind())
    
    op.add_column('events', sa.Column('recurrence_rule', sa.String(), nullable=True))
    op.add_column('events', sa.Column('preparation_time_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('responsibilities', sa.Column('effort_score', sa.Integer(), server_default='1', nullable=False))
    op.add_column('responsibilities', sa.Column('complexity_level', complexity_enum, server_default='LOW', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responsibilities', 'complexity_level')
    
    # Drop complexitylevel type
    sa.Enum(name='complexitylevel').drop(op.get_bind())
    
    op.drop_column('responsibilities', 'effort_score')
    op.drop_column('events', 'preparation_time_minutes')
    op.drop_column('events', 'recurrence_rule')
    op.drop_table('dependencies')
    # dependencytype drops with table drop usually? No, type persists.
    sa.Enum(name='dependencytype').drop(op.get_bind())
    # ### end Alembic commands ###
